# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d74225092b040a83b8a59f6e28f7ffb980358a5934bb5e1624bbfb0d1ff0f2d1a86fe020dbae250b8b5f04069e1d92c14a49b1c74d61cae2009cb95d7f0ffd9

beta:
  secret_key_base: 2xa0afa35b71415389115335259b03a9e0bfaafed2284d6c5bf8605dbe3e67d679aeb5aa06b90c7cc7f9ae7a6575bdd48214fee7f302c1b6f55635d25aef8d72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 2da0afa35b71415389115335259b03a9e0bfaafed2284d6c5bf8605dbe3e67d679aeb5aa06b90c7cc7f9ae7a6575bdd48214fee7f302c1b6f55635d26aef8d72
