window.App ||= {}
class App.Pages extends App.Base
  crossfading: false
  index: =>

  home: => 


    isChrome = /Chrome/.test(navigator.userAgent) and /Google Inc/.test(navigator.vendor)
    isSafari = /Safari/.test(navigator.userAgent) and /Apple Computer/.test(navigator.vendor)


    $('.table-cell').imagefill runOnce: true
    fadeInImage = ->
      $('.swap-image').css 'opacity': '1'
      afterImageFill()
      swapSrc()
      return

    afterImageFill = ->
      setTimeout resizeHome, 1000
      return

    swapSrc = ->
      $('.no-src').each ->
        $(this).attr 'src', $(this).attr('data')
        return


    resizeHome = ->
      targetHeight = $(window).height() - 300
      imgHeight = $('.swap-image').height()
      imgWidth = $('.swap-image').width()
      ratio = targetHeight / imgHeight
      console.log $(window).height(), targetHeight, imgHeight, ratio
      $('.home-image-logo').fadeOut 100
      $('.swap-image').css
        'transform': 'scale(' + ratio + ')'
        'top': $(window).height() / 2 - (imgHeight / 2)
        'left': $(window).width() / 2 - (imgWidth / 2)
      $('.main-header, #main-footer').delay(7000).addClass 'loaded'
      $('body, html').removeClass 'home-fixed'
      $('.home-image-wrapper').addClass 'animation-complete'
      return

    winHeight = $(window).height()
    winWidth = $(window).width()
    isMobile = $(window).width() <= 736
    if winWidth > 736
      $('body, html').addClass 'home-fixed'
    # //This is where the homepage image init starts
    $('.table-cell').imagesLoaded ->
      if isSafari
        setTimeout fadeInImage, 1000
      else 
        fadeInImage()
      return

    $(window).on 'resize', ->
      targetHeight = $(window).height() - 260
      imgHeight = $('.swap-image').height()
      imgWidth = $('.swap-image').width()



      ratio = targetHeight / imgHeight
      #console.log($(window).height(), targetHeight, imgHeight, ratio);
      $('.swap-image').css
        'transform': 'scale(' + ratio + ')'
        'top': $(window).height() / 2 - (imgHeight / 2)
        'left': $(window).width() / 2 - (imgWidth / 2)
      return

    $(document).on 'mouseenter', '.nav-img-switcher', (e) ->
      dataSwapId = undefined
      dataUrl = undefined
      newImage = undefined
      target = undefined
      dataUrl = $(this).data('url')
      dataSwapId = $(this).data('swap-id')
      target = $('#home-image-2')
      newImage = $('.image-container').find('#' + dataSwapId)
      unless $('.swap-image.shown').hasClass('pushed')
        $('.swap-image.shown').css 'opacity': '0'
        newImage.addClass('shown').css
          'visibility': 'visible'
          'opacity': '1'
      return

# ---
# generated by js2coffee 2.1.0

  @setHomeRollovers: =>
    $('.nav-img-switcher').each (e) ->
      if $(this).data 'url' != undefined
        i = new Image()
        i.src = $(this).data 'url'

    $(document).on 'mouseenter', '.nav-img-switcher', (e) ->
      dataUrl = $(this).data 'url'
      dataSwapId = $(this).data 'swap-id'
      target = $('#home-image-2')
      #target.attr 'src', dataUrl
      newImage = $('.image-container').find('#'+dataSwapId);
      $('.swap-image.shown').css
        'opacity':'0'
      newImage.addClass('shown').css
        'visibility':'visible'
        'opacity':'1'


    # i = $('#home-image-2').clone()
    # i.attr 'id', 'home-image-1'
    # styles =  $('#home-image-2').getStyleObject();
    # i.css 'display', 'none'
    # i.css styles
    # $('.image-container').prepend i

    # $(document).on 'mouseenter', '.nav-img-switcher', (e) ->      
    #   dataUrl = $(this).data 'url'

    #   if App.Pages.crossfading == true
    #     return
    #   App.Pages.crossfading = true   

    #   if $('#home-image-1').is(":visible")
    #     target = $('#home-image-2')
    #     target2 = $('#home-image-1')
    #   else
    #     target = $('#home-image-1')
    #     target2 = $('#home-image-2')
    #   target.attr 'src', dataUrl

    #   console.log target.attr 'src'
    #   console.log target2.attr 'src'

    #   if target.attr 'src' != target2.attr('src')    
    #     target.css 'opacity', 0
    #     target2.css 'opacity', 1
    #     target.show()
    #     target2.show()
    #     target.velocity {'opacity': 1}, {queue: false, duration: 'slow'}
    #     console.log 'fading in'+target.attr 'id'
    #     console.log 'fading out '+target2.attr 'id'
    #     target2.velocity {'opacity': 0}, {
    #       duration: 'slow',
    #       queue: false,
    #       complete: (e) ->
    #         console.log $(e).attr 'id'
    #         $(e).css 'display', 'none'
    #         App.Pages.crossfading = false
    #     }
      
